// Auto-generated mapping of neighborhood IDs to image names
// Run: node scripts/rename-neighborhood-images.js

export const neighborhoodImageMap: Record<string, string> = {
  "1": "shoreditch",
  "2": "clapham",
  "3": "brixton",
  "4": "camden",
  "5": "greenwich",
  "6": "notting-hill",
  "7": "hackney-wick",
  "8": "richmond",
  "9": "peckham",
  "10": "wimbledon",
  "11": "dalston",
  "12": "canary-wharf",
  "13": "dulwich",
  "14": "stratford",
  "15": "islington",
  "16": "wandsworth",
  "17": "hampstead",
  "18": "bethnal-green",
  "19": "battersea",
  "20": "crouch-end",
  "21": "bermondsey",
  "22": "ealing",
  "23": "putney",
  "24": "kentish-town",
  "25": "balham",
  "26": "hackney-central",
  "27": "fulham",
  "28": "walthamstow",
  "29": "kensington",
  "30": "tooting",
  "31": "angel",
  "32": "chiswick",
  "33": "deptford",
  "34": "st-johns-wood",
  "35": "stoke-newington",
  "36": "forest-hill",
  "37": "clapham-north",
  "38": "elephant-and-castle",
  "39": "marylebone",
  "40": "crystal-palace",
  "ny-1": "upper-west-side",
  "ny-2": "upper-east-side",
  "ny-3": "greenwich-village",
  "ny-4": "soho",
  "ny-5": "tribeca",
  "ny-6": "chelsea",
  "ny-7": "east-village",
  "ny-8": "lower-east-side",
  "ny-9": "harlem",
  "ny-10": "hells-kitchen",
  "ny-11": "williamsburg",
  "ny-12": "dumbo",
  "ny-13": "brooklyn-heights",
  "ny-14": "park-slope",
  "ny-15": "greenpoint",
  "ny-16": "bushwick",
  "ny-17": "cobble-hill",
  "ny-18": "fort-greene",
  "ny-19": "bedford-stuyvesant",
  "ny-20": "crown-heights",
  "ny-21": "astoria",
  "ny-22": "long-island-city",
  "ny-23": "flushing",
  "ny-24": "jackson-heights",
  "ny-25": "forest-hills",
  "ny-26": "south-bronx",
  "ny-27": "riverdale",
  "ny-28": "fordham",
  "ny-29": "st-george",
  "ny-30": "tottenville"
};

export const getNeighborhoodImageName = (id: string): string | undefined => {
  return neighborhoodImageMap[id];
};
